# roles/common/tasks/main.yml
---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - python3-pip
      - python3-dev
      - build-essential
      - libpq-dev
      - git
    state: present
