# inventory/hosts.yml
all:
  hosts:
    saleor:
      ansible_host: "{{ lookup('env', 'DROPLET_IP') }}"
      domain_name: "your-domain.com"
      enable_ssl: true
      email_address: "your-email@example.com"